---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: postgres:9-alpine
  commands:
  - sleep 10
  - psql -U postgres -d test -h database -c "SELECT version();"

services:
- name: database
  image: postgres
  environment:
    POSTGRES_DB: test
    POSTGRES_USER: postgres

...
